config/routes.rb
Rails.application.routes.draw do
  root "appointments#index"

  devise_for :users

  resources :doctors do
  resources :appointments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :appointments
         has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor
  before_action :set_appointment, only: [:show, :destroy]
  def index
    @appointments = current_user.appointments
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = current_user.appointment.new(appointment_params)
    if @appointment.save
      redirect_to appointments_path
    else
      render :new
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_path
  end
  private
  # def set_doctor
  #   @doctor = current_user.doctors.find(params[:doctor_id])
  # end

  def appointment_params
    params.require(:appointment).permit(:time, :date)
  end
  def set_appointment
    @account = current_user.appointment.find(params[:id])
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/appointments/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %></h2>
<hr />
<%= link_to "Add Appointment", new_doctor_appointment_path %>
<h3>Your Appointments</h3>
<ul>
  <% @appointments.each do |appointment| %>
    <li>
      <%= a.time %> - $<%= a.date %>
    </li>
  <% end %>
</ul>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/doctors/index.html.erb
<h1>Doctors#index</h1>
<p>Find me in app/views/doctors/index.html.erb</p>

app/views/doctors/new.html.erb
<h1>Doctors#new</h1>
<p>Find me in app/views/doctors/new.html.erb</p>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDoctorApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>